#!/bin/bash

function create_user(){

echo "=========== creation of user======="

read -p "enter a username" username

read -p "enter a password" password


sudo useradd -m "$username"

echo -e "$password\n$password" | sudo passwd "$username"


echo "=========== user cteated succesfully ========"

}


function user_del(){

echo "========= delete users ========="

read -p "enter a username" username

sudo userdel $username

echo "as wc is 0 the user is deleted"

}
create_user
user_del
